#! /bin/sh

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
bspc config border_width         4
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#6B4455"
bspc config active_border_color "#F49AC2"
bspc config focused_border_color "#F49AC2"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^3'
bspc rule -a discord desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true



# Autostart applications
sxhkd &
picom &
$HOME/.config/polybar/launch.sh &
$HOME/.fehbg &
st &
dunst &
sleep 1
notify-send "BSPWM Loaded" "with rolling waves" 
