#! /bin/sh
my_laptop_external_monitor=$(xrandr --query | grep 'VGA1')
if [[ $my_laptop_external_monitor = *connected* ]]; then
    xrandr --output LVDS1 --mode 1366x768 --rotate normal --left-of VGA1 --output VGA1 --primary --mode 1920x1080 --rotate normal
    bspc monitor LVDS1 -d 6 7 8 9 0 
    bspc monitor VGA1  -d 1 2 3 4 5
    bspc monitor LVDS1 -s VGA1
else 
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width         4
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#6B4455"
bspc config active_border_color "#F49AC2"
bspc config focused_border_color "#F49AC2"

bspc rule -a '*:zathura' state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^3'
bspc rule -a discord desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true



# Autostart applications
sxhkd &
picom &
$HOME/.config/polybar/launch.sh &
$HOME/.fehbg
st &
dunst &
sleep 1
notify-send "BSPWM Loaded"
megasync &
/usr/lib/kdeconnectd
udiskie --no-automount --tray &
